name: swagger-ui

services:
  front:
    image: swaggerapi/swagger-ui:latest
    hostname: swagger
    container_name: swagger
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      SWAGGER_JSON: "/swagger/api-swagger-2.0.json"
    volumes:
      - ../swagger:/swagger