name: headscale

services:
  coordinator:
    image: headscale/headscale:latest
    hostname: coordinator
    container_name: coordinator
    ports:
      - "8080:8080"
      - "9090:9090"
      - "50443:50443"
    volumes:
      - ./coordinator/config.yaml:/etc/headscale/config.yaml
      - ./coordinator/derp.json:/etc/headscale/derp.json
      - coordinator:/var/lib/headscale
    command: serve
    networks:
      - network

  frontend:
    hostname: frontend
    container_name: frontend
    build:
      context: ..
      dockerfile: ./docker/frontend/Dockerfile
    cap_add:
      - NET_ADMIN
    ports:
      - "8081:80"
    networks:
      - network
    depends_on:
      - coordinator

networks:
  network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

volumes:
  coordinator:
    driver: local