name: Release

on:
  push:
    tags:
      - 'v*'
#on:
#  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .npmrc file
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          registry-url: "https://registry.npmjs.org"
      - name: Install dependency
        run: | 
          npm install --no-fund --no-audit
      - name: Lint & Test
        run: |
          npm run lint
          npm test
      - name: Build
        run: |
          npm run build
          npm pack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        id: upload-artifact-step
        with:
          compression-level: '0'
          name: headscale-web-${{ github.ref_name }}.tgz
          path: headscale-web-*.tgz

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [build]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: headscale-web-${{ github.ref_name }}.tgz
          path: ${{ github.workspace }}
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: '**/headscale*.tgz'
          artifactErrorsFailBuild: true
          name: 'Release ${{ github.ref_name }}'

  docker-hub:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            sergeyitsib/headscale-web
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}