name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/headscale-web
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .npmrc file
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          registry-url: "https://registry.npmjs.org"
      - name: Install dependency
        run: | 
          npm install -g npm@latest
          npm install --no-fund --no-audit
      - name: Lint & Test
        run: |
          npm run lint
          npm test
      - name: Build
        run: |
          npm run build
          rm -rf node_modules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        id: upload-artifact-step
        with:
          name: headscale-web@${{ github.ref_name }}
          path: dist
      - name: Check Artifact Place
        run: |
          pwd
          ls -al
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: /home/runner/work/headscale-web/headscale-web@${{ github.ref_name }}.zip
          artifactErrorsFailBuild: true
          name: 'Release ${{ github.ref_name }}'
