name: Manual

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: headscale-web-v0.2.4
          path: ${{ github.workspace }}
      - name: Check FS
        run: |
          pwd
          ls -al